apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: irest
  name: irest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: irest
  template:
    metadata:
      labels:
        app: irest
    spec:
      containers:
        - image: quay.io/openshift-pipeline/irest:latest
          imagePullPolicy: Always
          name: irest
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 9090
              protocol: TCP